### PR TITLE
Upgrade ruby to 2.2.2 version.

### PR DESCRIPTION
**Pull request by gponsu**

### CODE REVIEW

**Comment by fearenales** [comment]
Hi @gponsu !

Thanks for your contribution! It's very important for us!

In order we can accept your PR, may I ask you to update the `Readme.md` file to cover the Ruby version change?

BTW, we've already created a tag for that, so you can include it to the `Readme.md` with the other version changes.

Any issue, let us know!
Thanks and regards

**Comment by gponsu** [comment]
@fearenales  Thanks to you for the project, and for the help!

A greeting! :)

**Comment by gullitmiranda** [comment]
@gponsu, thanks for your contribution!

I've added the [`v2.2.0`](https://github.com/azukiapp/docker-ruby/tree/v2.2.0) tag with the merge of your PR and both images are available at [Docker Hub](https://registry.hub.docker.com/u/azukiapp/ruby/).

:smile:

**Comment by gponsu** [comment]
Thank you very much to all! I'll delete the branch! :smile:

**Pull request merged**
